function timesheetMinutesLabel(minutes) {
  const h = Math.floor((minutes || 0) / 60);
  const m = Math.round((minutes || 0) % 60);
  return h > 0 ? `${h}h ${m}m` : `${m}m`;
}

function csvEscape(value) {
  const text = String(value ?? '');
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

function timesheetBreakMinutes(breakRow) {
  if (!breakRow || !breakRow.startTime || !breakRow.finishTime) return 0;
  const [startHours, startMinutes] = breakRow.startTime.split(':').map(Number);
  const [finishHours, finishMinutes] = breakRow.finishTime.split(':').map(Number);
  if (![startHours, startMinutes, finishHours, finishMinutes].every(Number.isFinite)) return 0;
  const start = startHours * 60 + startMinutes;
  let finish = finishHours * 60 + finishMinutes;
  if (finish < start) finish += 24 * 60;
  return Math.max(0, finish - start);
}

function formatTimesheetBreaks(breaks) {
  const validBreaks = (breaks || []).filter((breakRow) => breakRow.startTime && breakRow.finishTime);
  if (!validBreaks.length) return 'No detailed breaks';
  return validBreaks.map((breakRow) => {
    const status = breakRow.paid === true ? 'paid' : 'unpaid';
    return `${breakRow.startTime}-${breakRow.finishTime} ${status} ${timesheetMinutesLabel(timesheetBreakMinutes(breakRow))}`;
  }).join('; ');
}

function getTimesheetCalculator() {
  if (typeof module !== 'undefined' && module.exports) return require('./calculator.js');
  return { calculateShift: window.calculateShift, calculateTotals: window.calculateTotals };
}

function buildTimesheetRows(entries) {
  const { calculateShift } = getTimesheetCalculator();
  return (entries || []).map((entry) => {
    const shift = calculateShift(entry);
    return {
      date: shift.date,
      startTime: shift.startTime,
      finishTime: shift.finishTime,
      breaks: formatTimesheetBreaks(entry.breaks),
      unpaidBreakMinutes: shift.breakMinutes,
      paidBreakMinutes: shift.paidBreakMinutes,
      paidHours: shift.paidHours,
      grossPay: shift.grossPay,
      note: entry.note || '',
    };
  });
}

function buildTimesheetText({ entries, range, workerName = '', employer = '' }) {
  const { calculateTotals } = getTimesheetCalculator();
  const rows = buildTimesheetRows(entries);
  const totals = calculateTotals(entries || []);
  const lines = [
    'WageCheck AU Timesheet',
    `Pay period: ${range.start} to ${range.end}`,
  ];
  if (workerName) lines.push(`Worker: ${workerName}`);
  if (employer) lines.push(`Employer/site: ${employer}`);
  lines.push('', 'Shifts:');
  rows.forEach((row) => {
    lines.push(`${row.date} | ${row.startTime}-${row.finishTime} | Breaks: ${row.breaks} | Paid: ${row.paidHours.toFixed(2)}h | Gross estimate: $${row.grossPay.toFixed(2)}${row.note ? ` | Note: ${row.note}` : ''}`);
  });
  lines.push('', `Total paid hours: ${totals.paidHours.toFixed(2)}h`);
  lines.push(`Total gross estimate: $${totals.grossPay.toFixed(2)}`);
  lines.push('', 'Generated by WageCheck AU. Please verify against workplace rules, overtime, allowances, and payslip details.');
  return lines.join('\n');
}

function buildTimesheetCsv({ entries, range, workerName = '', employer = '' }) {
  const rows = buildTimesheetRows(entries);
  const csvRows = [
    ['WageCheck AU Timesheet'],
    ['Pay period', `${range.start} to ${range.end}`],
    ['Worker', workerName],
    ['Employer/site', employer],
    [],
    ['Date', 'Start', 'Finish', 'Breaks', 'Unpaid break minutes', 'Paid break minutes', 'Paid hours', 'Gross estimate', 'Note'],
    ...rows.map((row) => [row.date, row.startTime, row.finishTime, row.breaks, row.unpaidBreakMinutes, row.paidBreakMinutes, row.paidHours.toFixed(2), row.grossPay.toFixed(2), row.note]),
  ];
  return csvRows.map((row) => row.map(csvEscape).join(',')).join('\n');
}

if (typeof module !== 'undefined') {
  module.exports = { buildTimesheetRows, buildTimesheetText, buildTimesheetCsv, formatTimesheetBreaks };
}
