function timesheetMinutesLabel(minutes) {
  const h = Math.floor((minutes || 0) / 60);
  const m = Math.round((minutes || 0) % 60);
  return h > 0 ? `${h}h ${m}m` : `${m}m`;
}

function csvEscape(value) {
  const text = String(value ?? '');
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

function timesheetBreakMinutes(breakRow) {
  if (!breakRow) return 0;
  if (!breakRow.startTime || !breakRow.finishTime) return Math.max(0, Number(breakRow.durationMinutes) || 0);
  const [startHours, startMinutes] = breakRow.startTime.split(':').map(Number);
  const [finishHours, finishMinutes] = breakRow.finishTime.split(':').map(Number);
  if (![startHours, startMinutes, finishHours, finishMinutes].every(Number.isFinite)) return Math.max(0, Number(breakRow.durationMinutes) || 0);
  const start = startHours * 60 + startMinutes;
  let finish = finishHours * 60 + finishMinutes;
  if (finish < start) finish += 24 * 60;
  return Math.max(0, finish - start);
}

function formatTimesheetBreaks(breaks) {
  const validBreaks = (breaks || []).filter((breakRow) => (Number(breakRow.durationMinutes) || 0) > 0 || (breakRow.startTime && breakRow.finishTime));
  if (!validBreaks.length) return 'No breaks recorded';
  return validBreaks.map((breakRow) => {
    const status = breakRow.paid === true ? 'paid' : 'unpaid';
    const timeLabel = breakRow.startTime && breakRow.finishTime ? `${breakRow.startTime}-${breakRow.finishTime} ` : '';
    return `${timeLabel}${status} ${timesheetMinutesLabel(timesheetBreakMinutes(breakRow))}`;
  }).join('; ');
}

function getTimesheetCalculator() {
  if (typeof module !== 'undefined' && module.exports) return require('./calculator.js');
  return { calculateShift: window.calculateShift, calculateTotals: window.calculateTotals };
}

function buildTimesheetRows(entries) {
  const { calculateShift } = getTimesheetCalculator();
  return (entries || []).map((entry) => {
    const shift = calculateShift(entry);
    return {
      date: shift.date,
      startTime: shift.startTime,
      finishTime: shift.finishTime,
      breaks: formatTimesheetBreaks(entry.breaks),
      unpaidBreakMinutes: shift.breakMinutes,
      paidBreakMinutes: shift.paidBreakMinutes,
      paidHours: shift.paidHours,
      grossPay: shift.grossPay,
      note: entry.note || '',
    };
  });
}

function buildTimesheetText({ entries, range, workerName = '', employer = '' }) {
  const { calculateTotals } = getTimesheetCalculator();
  const rows = buildTimesheetRows(entries);
  const totals = calculateTotals(entries || []);
  const lines = [
    'WageCheck AU Timesheet',
    `Pay period: ${range.start} to ${range.end}`,
  ];
  if (workerName) lines.push(`Worker: ${workerName}`);
  if (employer) lines.push(`Employer/site: ${employer}`);
  lines.push('', 'Shifts:');
  rows.forEach((row) => {
    lines.push(`${row.date} | ${row.startTime}-${row.finishTime} | Breaks: ${row.breaks} | Paid: ${row.paidHours.toFixed(2)}h | Gross estimate: $${row.grossPay.toFixed(2)}${row.note ? ` | Note: ${row.note}` : ''}`);
  });
  lines.push('', `Total paid hours: ${totals.paidHours.toFixed(2)}h`);
  lines.push(`Total gross estimate: $${totals.grossPay.toFixed(2)}`);
  lines.push('', 'Generated by WageCheck AU. Please verify against workplace rules, overtime, allowances, and payslip details.');
  return lines.join('\n');
}

function buildTimesheetCsv({ entries, range, workerName = '', employer = '' }) {
  const rows = buildTimesheetRows(entries);
  const csvRows = [
    ['WageCheck AU Timesheet'],
    ['Pay period', `${range.start} to ${range.end}`],
    ['Worker', workerName],
    ['Employer/site', employer],
    [],
    ['Date', 'Start', 'Finish', 'Breaks', 'Unpaid break minutes', 'Paid break minutes', 'Paid hours', 'Gross estimate', 'Note'],
    ...rows.map((row) => [row.date, row.startTime, row.finishTime, row.breaks, row.unpaidBreakMinutes, row.paidBreakMinutes, row.paidHours.toFixed(2), row.grossPay.toFixed(2), row.note]),
  ];
  return csvRows.map((row) => row.map(csvEscape).join(',')).join('\n');
}

function htmlEscape(value) {
  return String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char]));
}

function money(value) {
  return `$${(value || 0).toFixed(2)}`;
}

function buildTimesheetPrintHtml({ entries, range, workerName = '', employer = '' }) {
  const { calculateTotals } = getTimesheetCalculator();
  const rows = buildTimesheetRows(entries);
  const totals = calculateTotals(entries || []);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>WageCheck AU Timesheet ${htmlEscape(range.start)} to ${htmlEscape(range.end)}</title>
  <style>
    body { font-family: Arial, sans-serif; color: #111827; margin: 24px; }
    h1 { margin-bottom: 4px; }
    .meta { margin: 4px 0; }
    table { border-collapse: collapse; width: 100%; margin-top: 18px; }
    th, td { border: 1px solid #d1d5db; padding: 8px; text-align: left; font-size: 12px; vertical-align: top; }
    th { background: #eef2ff; }
    .totals { margin-top: 18px; font-weight: 700; }
    .disclaimer { margin-top: 22px; color: #4b5563; font-size: 12px; }
  </style>
</head>
<body>
  <h1>WageCheck AU Timesheet</h1>
  <p class="meta">Pay period: ${htmlEscape(range.start)} to ${htmlEscape(range.end)}</p>
  ${workerName ? `<p class="meta">Worker: ${htmlEscape(workerName)}</p>` : ''}
  ${employer ? `<p class="meta">Employer/site: ${htmlEscape(employer)}</p>` : ''}
  <table>
    <thead><tr><th>Date</th><th>Start</th><th>Finish</th><th>Breaks</th><th>Paid hours</th><th>Gross estimate</th><th>Note</th></tr></thead>
    <tbody>
      ${rows.map((row) => `<tr><td>${htmlEscape(row.date)}</td><td>${htmlEscape(row.startTime)}</td><td>${htmlEscape(row.finishTime)}</td><td>${htmlEscape(row.breaks)}</td><td>${row.paidHours.toFixed(2)}h</td><td>${money(row.grossPay)}</td><td>${htmlEscape(row.note)}</td></tr>`).join('')}
    </tbody>
  </table>
  <div class="totals">Total paid hours: ${totals.paidHours.toFixed(2)}h<br>Total gross estimate: ${money(totals.grossPay)}</div>
  <p class="disclaimer">Generated by WageCheck AU. Please verify against workplace rules, overtime, allowances, and payslip details.</p>
</body>
</html>`;
}

if (typeof module !== 'undefined') {
  module.exports = { buildTimesheetRows, buildTimesheetText, buildTimesheetCsv, buildTimesheetPrintHtml, formatTimesheetBreaks };
}
